import blog1 from "./media/blogback1.jpg"
import blog2 from "./media/blogback2.jpg"
import blog3 from "./media/blogback3.jpg"

export const Blogs = [
  {
    key: 0,
    heading: "This is heading for Article 1",
    image: blog1,
    body: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid reprehenderit adipisci est exercitationem? Explicabo maxime dolore obcaecati sed quod labore placeat consequuntur rerum. Dolor omnis ipsum, quas consequatur porro eos atque facere? Debitis, voluptatum, corporis consequatur asperiores voluptates dicta, maiores eligendi unde tempore soluta quibusdam illo. Amet a pariatur alias in id accusantium maiores temporibus ut quod, qui nulla tempora, ipsa perferendis deserunt magni. Aperiam, veritatis blanditiis soluta eius maiores libero magnam, qui quidem tenetur iusto beatae culpa voluptas! Id, temporibus. Dolorum voluptatibus veniam ipsa delectus laborum soluta debitis fugiat fuga fugit, sequi quaerat distinctio? Dolor perferendis ea, accusantium nobis reprehenderit molestiae voluptatibus sequi saepe ad laboriosam dolorem at voluptate totam eaque ratione magnam unde fugit harum eos eveniet! Praesentium quam illum nostrum, animi soluta totam a deleniti voluptas blanditiis impedit veniam vitae provident? Nulla quis illum aliquam adipisci quasi, corporis dolores porro. Assumenda, nobis? Commodi sint repellendus exercitationem? Sit, harum ex maxime nisi eveniet quo cupiditate repudiandae ipsa quibusdam laudantium deserunt, saepe iste. Ipsum earum alias perspiciatis modi ullam magnam tempora officiis excepturi magni, repellat, esse odio? Accusamus, aspernatur perferendis magni illum explicabo voluptatem reprehenderit, ut sequi ipsum in qui consequatur nihil vitae itaque libero hic harum, nemo illo velit quidem a nobis quos beatae dolorum. Ex cumque voluptatum consectetur placeat quis provident, tempore eius recusandae error totam dolorum blanditiis facilis, vel praesentium delectus aliquam suscipit odio est, sequi excepturi mollitia incidunt. Alias nostrum consequuntur, saepe, corrupti pariatur voluptas aliquam sint nihil ipsam enim optio recusandae nesciunt tempore facere obcaecati odio cum quod ad quam suscipit deleniti. Numquam ipsum voluptates nostrum non natus dignissimos voluptatibus recusandae, quam inventore soluta sed, rem commodi illum sunt beatae hic, cum minus? Asperiores cumque eius ipsa pariatur repellat molestiae omnis facere voluptatum qui quis in ipsum ducimus quisquam velit voluptatibus, expedita explicabo laboriosam.",
  },
  {
    key: 1,
    heading: "This is heading for Article 2",
    image: blog2,
    body: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid reprehenderit adipisci est exercitationem? Explicabo maxime dolore obcaecati sed quod labore placeat consequuntur rerum. Dolor omnis ipsum, quas consequatur porro eos atque facere? Debitis, voluptatum, corporis consequatur asperiores voluptates dicta, maiores eligendi unde tempore soluta quibusdam illo. Amet a pariatur alias in id accusantium maiores temporibus ut quod, qui nulla tempora, ipsa perferendis deserunt magni. Aperiam, veritatis blanditiis soluta eius maiores libero magnam, qui quidem tenetur iusto beatae culpa voluptas! Id, temporibus. Dolorum voluptatibus veniam ipsa delectus laborum soluta debitis fugiat fuga fugit, sequi quaerat distinctio? Dolor perferendis ea, accusantium nobis reprehenderit molestiae voluptatibus sequi saepe ad laboriosam dolorem at voluptate totam eaque ratione magnam unde fugit harum eos eveniet! Praesentium quam illum nostrum, animi soluta totam a deleniti voluptas blanditiis impedit veniam vitae provident? Nulla quis illum aliquam adipisci quasi, corporis dolores porro. Assumenda, nobis? Commodi sint repellendus exercitationem? Sit, harum ex maxime nisi eveniet quo cupiditate repudiandae ipsa quibusdam laudantium deserunt, saepe iste. Ipsum earum alias perspiciatis modi ullam magnam tempora officiis excepturi magni, repellat, esse odio? Accusamus, aspernatur perferendis magni illum explicabo voluptatem reprehenderit, ut sequi ipsum in qui consequatur nihil vitae itaque libero hic harum, nemo illo velit quidem a nobis quos beatae dolorum. Ex cumque voluptatum consectetur placeat quis provident, tempore eius recusandae error totam dolorum blanditiis facilis, vel praesentium delectus aliquam suscipit odio est, sequi excepturi mollitia incidunt. Alias nostrum consequuntur, saepe, corrupti pariatur voluptas aliquam sint nihil ipsam enim optio recusandae nesciunt tempore facere obcaecati odio cum quod ad quam suscipit deleniti. Numquam ipsum voluptates nostrum non natus dignissimos voluptatibus recusandae, quam inventore soluta sed, rem commodi illum sunt beatae hic, cum minus? Asperiores cumque eius ipsa pariatur repellat molestiae omnis facere voluptatum qui quis in ipsum ducimus quisquam velit voluptatibus, expedita explicabo laboriosam.",
  },
  {
    key: 2,
    heading: "This is heading for Article 3",
    image: blog3,
    body: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid reprehenderit adipisci est exercitationem? Explicabo maxime dolore obcaecati sed quod labore placeat consequuntur rerum. Dolor omnis ipsum, quas consequatur porro eos atque facere? Debitis, voluptatum, corporis consequatur asperiores voluptates dicta, maiores eligendi unde tempore soluta quibusdam illo. Amet a pariatur alias in id accusantium maiores temporibus ut quod, qui nulla tempora, ipsa perferendis deserunt magni. Aperiam, veritatis blanditiis soluta eius maiores libero magnam, qui quidem tenetur iusto beatae culpa voluptas! Id, temporibus. Dolorum voluptatibus veniam ipsa delectus laborum soluta debitis fugiat fuga fugit, sequi quaerat distinctio? Dolor perferendis ea, accusantium nobis reprehenderit molestiae voluptatibus sequi saepe ad laboriosam dolorem at voluptate totam eaque ratione magnam unde fugit harum eos eveniet! Praesentium quam illum nostrum, animi soluta totam a deleniti voluptas blanditiis impedit veniam vitae provident? Nulla quis illum aliquam adipisci quasi, corporis dolores porro. Assumenda, nobis? Commodi sint repellendus exercitationem? Sit, harum ex maxime nisi eveniet quo cupiditate repudiandae ipsa quibusdam laudantium deserunt, saepe iste. Ipsum earum alias perspiciatis modi ullam magnam tempora officiis excepturi magni, repellat, esse odio? Accusamus, aspernatur perferendis magni illum explicabo voluptatem reprehenderit, ut sequi ipsum in qui consequatur nihil vitae itaque libero hic harum, nemo illo velit quidem a nobis quos beatae dolorum. Ex cumque voluptatum consectetur placeat quis provident, tempore eius recusandae error totam dolorum blanditiis facilis, vel praesentium delectus aliquam suscipit odio est, sequi excepturi mollitia incidunt. Alias nostrum consequuntur, saepe, corrupti pariatur voluptas aliquam sint nihil ipsam enim optio recusandae nesciunt tempore facere obcaecati odio cum quod ad quam suscipit deleniti. Numquam ipsum voluptates nostrum non natus dignissimos voluptatibus recusandae, quam inventore soluta sed, rem commodi illum sunt beatae hic, cum minus? Asperiores cumque eius ipsa pariatur repellat molestiae omnis facere voluptatum qui quis in ipsum ducimus quisquam velit voluptatibus, expedita explicabo laboriosam.",
  },
  {
    key: 3,
    heading: "This is heading for Article 4",
    image: blog2,
    body: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid reprehenderit adipisci est exercitationem? Explicabo maxime dolore obcaecati sed quod labore placeat consequuntur rerum. Dolor omnis ipsum, quas consequatur porro eos atque facere? Debitis, voluptatum, corporis consequatur asperiores voluptates dicta, maiores eligendi unde tempore soluta quibusdam illo. Amet a pariatur alias in id accusantium maiores temporibus ut quod, qui nulla tempora, ipsa perferendis deserunt magni. Aperiam, veritatis blanditiis soluta eius maiores libero magnam, qui quidem tenetur iusto beatae culpa voluptas! Id, temporibus. Dolorum voluptatibus veniam ipsa delectus laborum soluta debitis fugiat fuga fugit, sequi quaerat distinctio? Dolor perferendis ea, accusantium nobis reprehenderit molestiae voluptatibus sequi saepe ad laboriosam dolorem at voluptate totam eaque ratione magnam unde fugit harum eos eveniet! Praesentium quam illum nostrum, animi soluta totam a deleniti voluptas blanditiis impedit veniam vitae provident? Nulla quis illum aliquam adipisci quasi, corporis dolores porro. Assumenda, nobis? Commodi sint repellendus exercitationem? Sit, harum ex maxime nisi eveniet quo cupiditate repudiandae ipsa quibusdam laudantium deserunt, saepe iste. Ipsum earum alias perspiciatis modi ullam magnam tempora officiis excepturi magni, repellat, esse odio? Accusamus, aspernatur perferendis magni illum explicabo voluptatem reprehenderit, ut sequi ipsum in qui consequatur nihil vitae itaque libero hic harum, nemo illo velit quidem a nobis quos beatae dolorum. Ex cumque voluptatum consectetur placeat quis provident, tempore eius recusandae error totam dolorum blanditiis facilis, vel praesentium delectus aliquam suscipit odio est, sequi excepturi mollitia incidunt. Alias nostrum consequuntur, saepe, corrupti pariatur voluptas aliquam sint nihil ipsam enim optio recusandae nesciunt tempore facere obcaecati odio cum quod ad quam suscipit deleniti. Numquam ipsum voluptates nostrum non natus dignissimos voluptatibus recusandae, quam inventore soluta sed, rem commodi illum sunt beatae hic, cum minus? Asperiores cumque eius ipsa pariatur repellat molestiae omnis facere voluptatum qui quis in ipsum ducimus quisquam velit voluptatibus, expedita explicabo laboriosam.",
  },
  {
    key: 4,
    heading: "This is heading for Article 5",
    image: blog1,
    body: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid reprehenderit adipisci est exercitationem? Explicabo maxime dolore obcaecati sed quod labore placeat consequuntur rerum. Dolor omnis ipsum, quas consequatur porro eos atque facere? Debitis, voluptatum, corporis consequatur asperiores voluptates dicta, maiores eligendi unde tempore soluta quibusdam illo. Amet a pariatur alias in id accusantium maiores temporibus ut quod, qui nulla tempora, ipsa perferendis deserunt magni. Aperiam, veritatis blanditiis soluta eius maiores libero magnam, qui quidem tenetur iusto beatae culpa voluptas! Id, temporibus. Dolorum voluptatibus veniam ipsa delectus laborum soluta debitis fugiat fuga fugit, sequi quaerat distinctio? Dolor perferendis ea, accusantium nobis reprehenderit molestiae voluptatibus sequi saepe ad laboriosam dolorem at voluptate totam eaque ratione magnam unde fugit harum eos eveniet! Praesentium quam illum nostrum, animi soluta totam a deleniti voluptas blanditiis impedit veniam vitae provident? Nulla quis illum aliquam adipisci quasi, corporis dolores porro. Assumenda, nobis? Commodi sint repellendus exercitationem? Sit, harum ex maxime nisi eveniet quo cupiditate repudiandae ipsa quibusdam laudantium deserunt, saepe iste. Ipsum earum alias perspiciatis modi ullam magnam tempora officiis excepturi magni, repellat, esse odio? Accusamus, aspernatur perferendis magni illum explicabo voluptatem reprehenderit, ut sequi ipsum in qui consequatur nihil vitae itaque libero hic harum, nemo illo velit quidem a nobis quos beatae dolorum. Ex cumque voluptatum consectetur placeat quis provident, tempore eius recusandae error totam dolorum blanditiis facilis, vel praesentium delectus aliquam suscipit odio est, sequi excepturi mollitia incidunt. Alias nostrum consequuntur, saepe, corrupti pariatur voluptas aliquam sint nihil ipsam enim optio recusandae nesciunt tempore facere obcaecati odio cum quod ad quam suscipit deleniti. Numquam ipsum voluptates nostrum non natus dignissimos voluptatibus recusandae, quam inventore soluta sed, rem commodi illum sunt beatae hic, cum minus? Asperiores cumque eius ipsa pariatur repellat molestiae omnis facere voluptatum qui quis in ipsum ducimus quisquam velit voluptatibus, expedita explicabo laboriosam.",
  },
];
